"""empty message

Revision ID: 46307da0d347
Revises: 
Create Date: 2024-06-23 09:10:38.199017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46307da0d347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_model',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('in_cost', sa.VARCHAR(), nullable=True),
    sa.Column('out_cost', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code'),
    schema='openai_chat'
    )
    op.create_table('user',
    sa.Column('telegram_user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('current_discussion', sa.BigInteger(), nullable=True),
    sa.Column('current_chat_model', sa.Text(), nullable=False),
    sa.Column('usage_limit', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['current_chat_model'], ['openai_chat.chat_model.code'], ),
    sa.ForeignKeyConstraint(['current_discussion'], ['openai_chat.discussion.id'], use_alter=True),
    sa.PrimaryKeyConstraint('telegram_user_id'),
    schema='openai_chat'
    )
    op.create_table('discussion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('system_role', sa.Text(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('chat_model', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['chat_model'], ['openai_chat.chat_model.code'], ),
    sa.ForeignKeyConstraint(['user'], ['openai_chat.user.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='openai_chat'
    )
    op.create_table('transaction',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('chat_model', sa.Text(), nullable=True),
    sa.Column('in_message_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('out_message_id', sa.Integer(), nullable=True),
    sa.Column('in_used_tokens', sa.Integer(), nullable=True),
    sa.Column('out_used_tokens', sa.Integer(), nullable=True),
    sa.Column('in_cost', sa.VARCHAR(), nullable=True),
    sa.Column('out_cost', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['chat_model'], ['openai_chat.chat_model.code'], ),
    sa.ForeignKeyConstraint(['user'], ['openai_chat.user.telegram_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='openai_chat'
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('discussion', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['discussion'], ['openai_chat.discussion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='openai_chat'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message', schema='openai_chat')
    op.drop_table('transaction', schema='openai_chat')
    op.drop_table('discussion', schema='openai_chat')
    op.drop_table('user', schema='openai_chat')
    op.drop_table('chat_model', schema='openai_chat')
    # ### end Alembic commands ###
