"""initial

Revision ID: 66bc6b535292
Revises: 
Create Date: 2023-06-25 13:38:18.956444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bc6b535292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_chat',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('active_chat', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['active_chat'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('active_chat')
    op.drop_table('chat')
    # ### end Alembic commands ###
