"""empty message

Revision ID: 7ec8d296f39e
Revises: 
Create Date: 2024-04-18 19:12:45.754939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec8d296f39e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('system_role', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='openai_chat'
    )
    op.create_table('users',
    sa.Column('telegram_user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id'),
    schema='openai_chat'
    )
    op.create_table('active_chat',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('active_chat', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['active_chat'], ['openai_chat.chat.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    schema='openai_chat'
    )
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['openai_chat.chat.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='openai_chat'
    )
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.drop_table('message', schema='openai_chat')
    op.drop_table('active_chat', schema='openai_chat')
    op.drop_table('users', schema='openai_chat')
    op.drop_table('chat', schema='openai_chat')
    # ### end Alembic commands ###
