"""empty message

Revision ID: 97d9bef3e2f6
Revises:
Create Date: 2024-04-20 13:32:47.375787

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97d9bef3e2f6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("system_role", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="openai_chat",
    )
    op.create_table(
        "users",
        sa.Column(
            "telegram_user_id", sa.BigInteger(), autoincrement=False, nullable=False
        ),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("telegram_user_id"),
        schema="openai_chat",
    )
    op.create_table(
        "active_chat",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("active_chat", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["active_chat"],
            ["openai_chat.chat.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        schema="openai_chat",
    )
    op.create_table(
        "message",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["openai_chat.chat.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="openai_chat",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message", schema="openai_chat")
    op.drop_table("active_chat", schema="openai_chat")
    op.drop_table("users", schema="openai_chat")
    op.drop_table("chat", schema="openai_chat")
    # ### end Alembic commands ###
